import React from "react";
import CheckoutItem from "../components/CheckoutItem";
import Nav from "../components/Nav";
import Head from "next/head";

/* import { useSelector } from "react-redux";
import { selectItems } from "../slices/basketSlice"; */

import CheckoutBody from "../components/CheckoutBody";

/* Add new component CheckoutBody */
function cartpage() {
  /*  const items = useSelector(selectItems);

  const itemCost = 5; */

  return (
    <div>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <CheckoutBody />
    </div>
  );
}

export default cartpage;
